/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CurrencyConverter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;

class AppTest extends App {
    @Test
    void testShowGreeting() {
        String greeting1 = showGreeting();
        String greeting2 = "********************************************************\n" +
                           "********************************************************\n" +
                           "****************** Currency Converter ******************\n" +
                           "********************************************************\n" +
                           "********************************************************\n";
        assertEquals(greeting1, greeting2);
    }

    @Test
    void testShowExitGreeting() {
        String exit1 = showExitGreeting();
        String exit2 = "********************************************************\n" +
                       "********************************************************\n" +
                       "************************* BYE **************************\n" +
                       "********************************************************\n" +
                       "********************************************************\n";
        assertEquals(exit1, exit2);
    }


    @Test
    void testWrongCurrencyMessage() {
        String wrongCurrency = wrongCurrencyMessage("Yen");
        String wrongCurrencyMessage = "Yen is not a valid currency \nPlease enter again!";
        assertEquals(wrongCurrency, wrongCurrencyMessage);
    }


    @Test
    void testFromCurrency() {
    }

    @Test
    void testToCurrency() {
    }

    @Test
    void testSumHelper() {
        List<Pair<CurrenciesIndex, Double>> sumList = new ArrayList<>();
        sumList.add(new Pair<CurrenciesIndex, Double>(CurrenciesIndex.USD, 10.0));
        sumList.add(new Pair<CurrenciesIndex, Double>(CurrenciesIndex.EURO, 10.0));
        sumList.add(new Pair<CurrenciesIndex, Double>(CurrenciesIndex.POUND, 10.0));
        double sum1 = sumHelper(sumList, CurrenciesIndex.AUD);
        double sum2 = 48.7;
        assertEquals(sum1, sum2);
    }
}
